sudo: false
language: go
go:
  - 1.4

before_install:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - ruby --version
  - rvm --version
  - bundle --version
  - gem --version
  # lets check the following, because if GOPATH is set properly, we can set PATH
  # more intelligently in the install steps
  - go env
  - echo $PATH

install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - bundle install --jobs 3 --retry 3
  - script/build

script:
  - go test ./...
  - bundle exec rake features

branches:
  except:
    - gh-pages

cache:
  directories:
    - vendor/bundle
