sudo: false
language: go
go:
  - 1.7
  - 1.8

branches:
  except:
    - gh-pages

addons:
  apt:
    packages:
      - zsh

install:
  - bundle install --jobs 4 --retry 3 --path vendor/bundle
  - script/build

script:
  - go test ./...
  - bundle exec cucumber -s --tags=~@wip --tags=~@recent-git-only

before_cache:
  - bundle clean

cache:
  directories:
    - vendor/bundle
