language: go
go:
  - 1.4

before_install:
  # make sure we have git, bash, and zsh installed to test on
  - sudo apt-get update -qq
  - sudo apt-get install -qq zsh git
  # we need Ruby too, for our Aruba feature integration tests
  - rvm use 2.2.1 --install --binary --fuzzy
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - ruby --version
  - rvm --version
  - bundle --version
  - gem --version
  # lets check the following, because if GOPATH is set properly, we can set PATH
  # more intelligently in the install steps
  - go env
  - echo $PATH

install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - bundle install --jobs 3 --retry 3
  - script/bootstrap
  - script/build

script:
  - go test ./...
  - bundle exec rake features

branches:
  except:
    - gh-pages
