sudo: false
language: go
env:
  - GO15VENDOREXPERIMENT=1
go:
  - 1.6
  - 1.7
  - 1.8

before_install:
  - curl -fsSL https://ci-cache.s3.amazonaws.com/tmux-zsh.ubuntu.tgz | tar -xz -C ~

install:
  - bundle install --jobs 3 --retry 3 --path vendor/bundle
  - script/build

script:
  - go test ./...
  - bundle exec cucumber -s --tags=~@wip --tags=~@recent-git-only

branches:
  except:
    - gh-pages

cache:
  directories:
    - vendor/bundle
