[application]
name = "scmpuff"
authors = ["Matthew Rothenberg <mroth@mroth.info>"]

[dependencies]
"github.com/spf13/cobra" = "f8e1ec56bdd7494d309c69681267859a6bfb7549"
"github.com/spf13/pflag" = "370c3171201099fa6b466db45c8a032cbce33d8d"
